### ISSUE TITLE
Resume CodeTour when navigated away from step

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#102]
Many developers use CodeTour to present code. Sometimes, during conversation, the presenter navigates away from code. Then, it's hard to go back to the original location without missing a few steps. 
If each step is helping a user upgrade or write code, missing a few steps would break the codebase.

**Comment by lostintangent** [comment]
Does the [status bar](https://github.com/vsls-contrib/codetour#status-bar) help here? We added that feature for this exact use case 👍

**Comment by gsmile** [comment]
That's great! However, customers don't think it's a very discoverable location since I've heard a request for returning to current location from a presentation a few times.
What if we add a button or glyph under the Tree so that a person who is running a presentation can quickly go back to the current step?

**Comment by lostintangent** [comment]
Under the `CodeTour` tree? One other thing I'd mention is that the current tour and step is highlighted in the `CodeTour` tree, and so that could be another mechanism for folks to identity and resume the current step?

<img width="300px" src="https://user-images.githubusercontent.com/116461/98453627-25a9a400-2110-11eb-934d-dce1742b4bc8.png" />

**Comment by gsmile** [comment]
The feedback I have received is that there is no fast or intuitive way to resume the current step when they navigate away from the tour. These are high-pressure situations when developers are presenting or explaining code to a lot of people. Perhaps it is a learned behaviour but it would be helpful if we can make it easier to go back to the current step. Do you have any suggestions on how this can be achieved?

**Comment by lostintangent** [comment]
One other thing I forgot to mention! We also add a `CodeTour: Resume Tour` command to the command palette, which allows you to jump back to the current step:

<img width="600px" src="https://user-images.githubusercontent.com/116461/98453892-0f511780-2113-11eb-8671-7b578369e124.png" />

Between the command palette option, the `CodeTour` tree and the status bar item, I think we're taking advantage of almost every option we have, in order to accomodate different user workflows. The status bar and command palette have the benefit of being "globally available", and so a user could quickly use them, regardless what side bar tab they have focused.

We could add a keyboard shortcut to resume the current tour? Other than that, I can't think of any other options unfortunately, besides what we're already providing.

**Comment by lostintangent** [comment]
I also just updated the `CodeTour` tree to display the current tour and step as a message at the top. This way, the `CodeTour` tree makes it super clear what tour and step you're currently on.

<img width="300px" src="https://user-images.githubusercontent.com/116461/98473639-f8113900-21a9-11eb-9225-b7a073828c46.png" />

After thinking about this for a while, I think we just need to educate users on how to use the tree, command palette and status bar (based on their preferred workflow). I don't believe we have any other good options besides this, and I also think that we're already providing very idiomatic options for VS Code, based on the way that other extensions behave.

**Comment by gsmile** [comment]
Thanks for implementing a change! What if the text said "Go to current step" and was clickable to take the person to the current step?

**Comment by lostintangent** [comment]
Unfortunately, that new label I added isn’t clickable. So I think that the existing tree view, status bar item and command palette are out best options right now.

**Comment by gsmile** [comment]
Revisiting this issue again as I'm hearing a lot of devs comment on this request: is there any way we can add a Resume button to the top of the window, or another easy, clickable way to resume a tour?

**Comment by lostintangent** [comment]
@gsmile I believe this is what the [status bar button](https://github.com/vsls-contrib/codetour#status-bar) currently provides? Whenever you're in a tour, it provides a globally-available, one-click mechanism to resume the tour. I'm not aware of any other great option we have to expose this, since the status bar is effectively the de-facto way of providing an easy entry point for common/valuable commands.

**Comment by gsmile** [comment]
Thanks for the context. I agree that the status bar button is the functionality that's needed but most people don't use or see the status bar text. I'm thinking we'll keep this issue until the editor allows a better way to expose this because this feedback keeps coming up.
