### ISSUE TITLE
Markdown export

### ISSUE THREAD

**Issue by gracegtaylor** [microsoft/codetour#112]
In some situations, developers want to look at documentation without exporting code. If there were a way to export CodeTours into .md files so that developers can view docs without cloning the repo, it may enable scenarios for quick sharing on Github.

**Comment by LucianoBestia** [comment]
Try to have a look at my project: https://github.com/LucianoBestia/codetour_export_to_md.

**Comment by lostintangent** [comment]
I'd like to expand the current "Export tour" functionality to include support for markdown as well. We've already got a tour-to-markdown converter (as part of the initial notebook implementation), and so we could look into reusing that for this as well.

**Comment by lostintangent** [comment]
With the [launch of GitHub.dev](https://twitter.com/lostintangent/status/1425901618780729345?s=21), I believe that devs now have an easy way to share a tour with people that aren't otherwise using VS Code. That said, I'm going to close this as resolve, but please let me know if there are other considerations for needing the markdown support. Thanks!
