### ISSUE TITLE
UI for pointing out prompt commands

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#116]
As CodeTour gains traction for dev communities, a lot of tutorials and walkthroughs involve upgrading or installation processes, e.g. dev containers or azure functions. In these scenarios, the steps involve explaining prompt commands.
If CodeTour could bring the developer's attention to explain a prompt command or popup, it would be helpful in improving upgrade or setup flows for certain technologies.

**Comment by lostintangent** [comment]
Are there any specific examples we could use to spec out the desired behavior? Maybe we could write out a user workflow for one of the extensions you mentioned, and call out what we’d want the new behavior to be?

**Comment by gsmile** [comment]
Do VS Code extensions allow for prompts or pop-ups that show up beside a toast, or an overlay across the screen?
Here are some examples of user workflows:
When an author wants to create a step pointing towards an action in the status bar, they can right-click the status bar and pick "Add CodeTour Step" to that section. This will then create a toast that explains the action in the status bar.
When an author wants to create a step pointing towards a toast, when the toast pops up, they can right-click the toast and pick "Add CodeTour Step" to show up beside that toast.

One tutorial I was trying to replicate was the Dev Containers tutorial, and encountered some of those limitations: https://code.visualstudio.com/docs/remote/containers-tutorial

**Comment by lostintangent** [comment]
Unfortunately, there isn't currently a way to add a context menu to status bar buttons or toasts. And so I don't think I there'd be any natural way to author a tour step that pointed on either of these.

For now, I think the best workaround would be to take a screenshot of the toast/status bar item, and embedding it as a picture in a tour step. That way, you could visually call it out for the reader.

Additionally, since status bar buttons are just commands, the tour could also include a command link that the user could click in the step, in order to automate the action of clicking the status bar button.

Neither of these options are ideal, but, we may be able to depriorize these for now, if we think they're primarily needed for onboarding to a VS Code extension. If we initially focus on training/codebase learning scenarios, we may be able to put this time on the backlog and revisit it later?

**Comment by gsmile** [comment]
Ok sounds good, thank you for coming up with alternatives given the limitations. I'll change the prioritization.

**Comment by lostintangent** [comment]
Closing this for now, since there isn't a way to do this, and it doesn't sound like it's on the VS Code backlog anytime soon. So we can re-open it as we hear more feedback 👍🏻
