### ISSUE TITLE
Navigating through tour does not update file tree in sidebar 

### ISSUE THREAD

**Issue by bpmct** [microsoft/codetour#118]
The workspace sidebar does not seem to reflect the current file open in CodeTour:
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/22407953/101556424-ac4fdc00-396f-11eb-8506-701d48dc35f6.gif)

It looks like this used to work in an old version of CodeTour (taken from README.md):
![77705325-9682be00-6f7c-11ea-9532-6975b19b8fcb](https://user-images.githubusercontent.com/22407953/101556378-93472b00-396f-11eb-9e39-2abdb8a24c60.gif)

**Comment by lostintangent** [comment]
Hey! I believe this behavior is because the tour is associated with a specific Git ref, and therefore, the files you're navigating are actually different than the one in your file explorer. If you create a new tour, and selected `None` for the git ref, then you should see the file explorer be highlighted as you navigate the tour. I'll have to take a look and see if there's a way to support the file explorer highlighting for arbitrary git refs.

**Comment by bpmct** [comment]
@lostintangent That was it, thanks! 🤦 Should I close this issue @lostintangent?

**Comment by gsmile** [comment]
Thanks! I've closed this issue now.
