### ISSUE TITLE
Code tours logo usage in browser extension

### ISSUE THREAD

**Issue by qmenoret** [microsoft/codetour#121]
Hello!

I've been working on building a browser extension to run code tours directly in github (without the need of codespace or vscode). I released the first version recently (chrome and firefox), and I currently use the logo of code tour for the extension: https://chrome.google.com/webstore/detail/code-tours-github/emmipndjppboloecpfgnckbkcehhhpkc/

I'd like to know if that is an issue, I have no problem to get a custom logo designed for the extension, but I thought it would be nice to use the official code tour logo. Let me know what you think, happy to take it down if you think it's wrong 🙂

**Comment by lostintangent** [comment]
Hey! This is so awesome 😎 I'll update the readme to call this out. Is the extension open source? I'd be curious to see which set of your features you implemented 👍

**Comment by qmenoret** [comment]
Yep it's open source. You can find the code here: https://github.com/doctolib/code-tours-github
For now it's still very early so, you can basically select a tour and play it (meaning it will walk you through all steps). Pretty basic, still need to implement other things like showing highlighting a specific part of the code for instance (now i can only highlight a line).
Happy to get your thoughts if you try it out 😊

**Comment by gsmile** [comment]
@qmenoret Thank you for creating this extension! I've played around with it. It looks great and I think it would be helpful for many people. If some of the formatting for the display of the tour itself could be visually differentiated from code so it's easier to skim, I think it'll help with the usability. Great work!

**Comment by qmenoret** [comment]
Wow thanks a lot for the feedback! Yeah I'm sure there are a lot of way to improve the formatting. I'll give it a go, but do you have any specific suggestion? Happy to get your insights if any 😊

**Comment by gsmile** [comment]
I love how easy it is to view CodeTours via the browser using a button click. 
Since CodeTour is a popular tool for learning and accessibility, here are a few suggestions that improve the usefulness of the tool in the browser:
- If the tour box uses a different font for the body text, i.e. a Sans-Serif font, and the Previous/Next button uses the Github green, it could be a quick way to improve the accessibility of the extension by a lot.
- The verbiage of the CodeTour button on the repo page could be consistent with the rest of the Github buttons, to say "View CodeTours" instead of "Code Tour":
![image](https://user-images.githubusercontent.com/12738587/105883659-1894a680-5fd5-11eb-83b7-2c4f5d7d93df.png)
- I also notice that after I take a tour for the first time, and I navigate back to the main repo page, the CodeTour button disappears. I am using Chrome version 87.0.4280.141 on a Surface laptop.

Thanks so much for taking the time to create this extension. :)
