### ISSUE TITLE
Can you please add tags for existing releases?

### ISSUE THREAD

**Issue by GitMensch** [microsoft/codetour#127]
As you likely know you can tag old commits, too, and you can even have the correct date for them using [`GIT_COMMITTER_DATE`](https://git-scm.com/docs/git-commit#_commit_information).

It would be very nice to have old releases tagged and also tags for upcoming versions as this eases following the extension's development a lot. Ideally a new tag automatically will trigger publishing the extension so this actually leads to "less work", too.

**Comment by lostintangent** [comment]
Hey! 👋 Could you share more details about the workflow where tagged released would be helpful for you? We currently maintain the [CHANGELOG](https://github.com/microsoft/codetour/blob/main/CHANGELOG.md) to make it easy to track version history. This file is also displayed within VS Code (on the extension details page), which makes accessing it a little more convenient for many users, as opposed to relying on a GitHub releases page.

Additionally, since VS Code already allows you to install older versions of the extension, the value of GitHub releases are also potentially lower, since it’s easier to install the extension in-editor, as opposed to grabbing a VSIX and installing it “manually”.

**Comment by GitMensch** [comment]
Thank you for considering this.

> I suppose the GitHub releases would allow you to opt-in to getting notifications when a new extension version is released?

Yes, that subscription is quite useful, especially in a corporate environment where auto-updating is completely locked.

But the release page is only a secondary part (although it is quite useful to simply download an attached vsix from there after clicking on the release notification then to go to the marketplace, copy the download link, adjust it to a potential older version, ...).

My main note was about the git tags (which easily can be used as release, that's what most CIs do) as those help to actually check-out a specific version, run git bisect between "known good tag, known bad tag" and similar.

**Comment by lostintangent** [comment]
Ah I see. Out of curiosity: do you run Git bisect like this in order to do security scans/audits of extension updates?

**Comment by GitMensch** [comment]
Bisecting to check for errors (currently none found, but you always know what you miss when you do), comparing tags for minor audits (no bigger security scans... yet) - and without the tags it is for both cases always a lookup "What hash was that?"
