### ISSUE TITLE
Can't set a breakpoint by mouse click

### ISSUE THREAD

**Issue by vchirikov** [microsoft/codetour#130]
Subj. Also codetour icon (css: `ced-1-TextEditorDecorationType1-2`) overlaps with breakpoint icon.

**Comment by lostintangent** [comment]
Hey! Just to confirm: are you saying that when a line of code has a CodeTour step associated with it, you aren't able to set a breakpoint on that line? Because the CodeTour glyph gets in the way? If so, I'll have to look into this to see if there's a way to fix that.

In the meantime, you can hide the CodeTour glyphs entirely, by clicking the little eye icon in the `CodeTour` tree in the `Explorer` tab. Let me know if that's a sufficient workaround 👍 

![image](https://user-images.githubusercontent.com/116461/107696468-d753f600-6c66-11eb-96ad-57c88b87da80.png)

**Comment by vchirikov** [comment]
> you aren't able to set a breakpoint on that line? 

true (it is possible with keyboard shortcut)

> hide the CodeTour glyphs entirely

thanks, your workaround works fine

![repro](https://user-images.githubusercontent.com/40987940/107742708-9d472a80-6d20-11eb-9a13-d106ae6a0f10.gif)

**Comment by gsmile** [comment]
Great, I'm going to close this issue.
