### ISSUE TITLE
Add CodeTour tags inside code for tour resiliency

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#135]
Most developers want a one-time investment experience when it comes to CodeTour. Attaching CodeTour tags inside the code so that the steps are attached to tags instead of line numbers would help make sure that tours don't become outdated too quickly.

As a tour viewer:
1. I click the "Play" button and the tour plays in the codebase.
2. I see that there are CodeTour tags that look like "//CT 2.2 - Starting the tree" where the first part denotes the step and the second part denotes the title of the step.
3. If I am not viewing a CodeTour, I am able to hide the CodeTour tags in the codebase.

As a tour author:
1. I create a CodeTour step using the existing flow, and once I am done, I click "Save Step" and a CodeTour tag gets inserted into code.
2. I have the option to remove all CodeTour tags from my codebase or add all CodeTour tags to my codebase via an icon in the sidebar.
3. If I want to remove all CodeTour tags from the codebase, the steps will be attached to lines of code, not tags.

**Comment by lostintangent** [comment]
Since we'd be adding actual comments to the code base, we unfortunately wouldn't be able to hide these tags from the viewer. They'd represent an actual line of code, and VS Code doesn't support the notion of hiding lines from the editor. Do you think that will change the appeal of this solution for some folks? Since the tours wouldn't get taken often, but the markers would always be in the codebase?

**Comment by lostintangent** [comment]
@gsmile Since we're going to focus on regex right now, should we downgrade this to a P2/P3?

**Comment by lostintangent** [comment]
Closing in favor of #141.
