### ISSUE TITLE
Feature Request: right-click "Add Step" in CodeTour browser side panel

### ISSUE THREAD

**Issue by dsschnau** [microsoft/codetour#139]
This context menu seems like a great place for an "Add Step" feature.

![image](https://user-images.githubusercontent.com/1373329/108901605-111ee800-75e9-11eb-8ebc-4ccadae0b4b9.png)

**Comment by gsmile** [comment]
Thank you for this suggestion, @dsschnau! We will look into prioritizing this in our backlog.

**Comment by lostintangent** [comment]
What would the expected behavior be in this case? To add a new step below the selected step? That's how PowerPoint works if you right-click a slide and select `Add New`. But I wanted to confirm that this matched your expectations as well! 👍

**Comment by dsschnau** [comment]
@lostintangent  That's exactly what I was thinking 🙂

**Comment by lostintangent** [comment]
@dsschnau One last question: since this gesture wouldn't be associated with a file/line/folder, the only type of step that we could create is a "content" step. Is that what you'd expect here? For example, you'd right-click a step, select `Add Step Below` and then you'd get a comment box to fill in, just like if you ran the `CodeTour: Add Tour Step` command while editing a tour.

**Comment by dsschnau** [comment]
I think that makes sense 🙂

Maybe down the line it could change to handle specifying file/line/folder,
but I think it's a great "first step".

**Comment by lostintangent** [comment]
Alright cool. This has been added to `v0.0.46`, which is being published to the marketplace right now. Let us know what you think and we can iterate on the experience with you. Thanks!
