### ISSUE TITLE
Saving tour step places tour into Preview mode

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#140]
Developers have commented that the 3 modes are confusing. After a developer clicks Save, they would expect to be brought to Preview mode so that they can click reference links and shell commands in the step.

**Comment by lostintangent** [comment]
After the user clicks save and we put them back into preview mode, would you expect for the tour to stay in preview mode if they navigate to previous/next steps? (I'm guessing "yes") Also, would you expect for the "comment bar" to still be visible in the editor, so that they can still add new steps by clicking? (I'm also assuming "yes"). Right now, the "comment bar" is only visible when editing, and so to do this right, I just want to make sure I'm aligned on your expectations here 👍

**Comment by gsmile** [comment]
I think all of that sounds good. Thank you.

**Comment by lostintangent** [comment]
This has been fixed and published via `v0.0.45`. Let me know if you have any further feedback!
