### ISSUE TITLE
"Go to beginning of file" shortcut is triggering "second key of chord"

### ISSUE THREAD

**Issue by badsyntax** [microsoft/codetour#151]
I initially created this bug report in the vscode repo (https://github.com/microsoft/vscode/issues/119445), please see that issue report for more detail. I since discovered it's due to this extension, as disabling this extension fixes the issue.

**Comment by lostintangent** [comment]
This is fixed in `v0.0.48`, which is being published to the marketplace right now.

**Comment by badsyntax** [comment]
Thanks. It's be useful to reference commits against issues. It'd be useful to see the fix. Also why are there no tests to prevent regressions?

**Comment by lostintangent** [comment]
This bug wasn't a regression. It was a result of introducing a new keybinding, that wasn't "narrow" enough. And so the fix was to only enable the keybinding when the end-user isn't actively editing a file or terminal ([code](https://github.com/microsoft/codetour/blob/b3822a6c8368d757144440cdef069af782420fdc/package.json#L607)).
