### ISSUE TITLE
Add protocol handler to open tour from gist by clicking on a link.

### ISSUE THREAD

**Issue by plisy** [microsoft/codetour#154]
Implementing VS Code's [Protocol Handler API](https://code.visualstudio.com/updates/v1_23#_protocol-handler-api) for opening tours from gists would allow scenarios like dropping a link for an exported tour into documentation.

E.g. 

```
[Start in VS Code](vscode://vsls-contrib.codetour/openTour?url=https%3A%2F%2Fgist.github.com%2Fplisy%2F24c5060c749bda358f279b08c4570344)
```

**Comment by lostintangent** [comment]
Hey! It's not exactly what you're asking for, but as an FYI, the [GistPad extension](https://aka.ms/gistpad) supports this right now. It has a protocol handler for opening any gist (or repo), and if you right-click a gist in the tree, you can select the `Copy GistPad URL` menu in order to generate the full deep link for a specific gist.

<img width="500px" src="https://user-images.githubusercontent.com/116461/113491028-a9c74400-9482-11eb-8483-534f3f5a742e.png" />

When you have the GistPad extension installed, the CodeTour tree will have a new context-menu for tours, that allow you to export them to a gist. And so together, that makes it easy to record a tour, export it to a gist and then share a link with others:

<img width="500px" src="https://user-images.githubusercontent.com/116461/113491105-0dea0800-9483-11eb-8453-47f9568060ad.png" />

Would that be helpful at all?

**Comment by lostintangent** [comment]
I'm going to close this as resolved for now, assuming that the GistPad handler is sufficient? But, please reopen this if it's not. Thanks!
