### ISSUE TITLE
Visual Studio support

### ISSUE THREAD

**Issue by davidglassborow** [microsoft/codetour#43]
Love the idea, and whilst we use visual studio code for smaller pieces of work, our many large code base is worked on in Visual Studio 2019.  This feature would be great for documenting the various subsystems and cross cutting concerns, just wondered if you have any thoughts on how easy this would be to make into a VS extension ?

**Comment by lostintangent** [comment]
Adding Visual Studio support is definitely in the plans! We're simply starting with a single editor (VS Code) so that we can flesh out the UX/concepts first, before trying to scale it to other tools. We'll use this issue to track progress on that conversation, and please let us know about any feedback on the VS Code experience. That will help us get the confidence we need that we're ready to start expanding client support. Thanks!

**Comment by gsmile** [comment]
We are planning to enable the VS experience by creating a playback experience first, then an experience for editing.
The playback experience should work with the VS Code CodeTour files, while enabling editing CodeTours via JSON file.
The editing experience should include a visual UI for editing and recording tours.

**Comment by lostintangent** [comment]
Right now, the underlying tour file is a bit of an implementation detail, and so we should probably confirm that we're happy with the schema before we add another client on top of it. Otherwise, it will become harder to change over time. In particular, I suspect the schema will need to change once we address tour resiliency, and so we might want to figure out our plan for that soon.

Additionally, the player has become fairly rich (e.g. shell command links, code block injection, tracking tour progress, directory steps), and so I wonder if it makes sense to define the scope we'd want to start with for VS. Unless we'd want to just implement the entire player surface area to begin with?

**Comment by gsmile** [comment]
That's a great point. I thought we had alignment that it makes sense to first enable a VS playing experience that's similar to how it works in VS Code, so that existing tours work on both VS and VS Code. The implementation could change but I thought we could make it so that existing tours don't break, but if that's not the case, we can create a new plan.
The player has become fairly rich, so when our VS dev returns from vacation, I can sync with him on bandwidth and progress.

**Comment by gsmile** [comment]
That's a great point. I thought we had alignment that it makes sense to first enable a VS playing experience that's similar to how it works in VS Code, so that existing tours work on both VS and VS Code. The implementation could change but I thought we could make it so that existing tours don't break, but if that's not the case, we can create a new plan for this scenario so that we keep the experience consistent.
I agree that the player has become fairly rich, so when our VS dev returns from vacation, I can sync with him on bandwidth and progress.

**Comment by lostintangent** [comment]
Closing this for now, since I won't likely have the time/expertise to invest in this any time soon. If the community would like to help support it, the CodeTour format is documented in the readme, and so it could be implemented at any time. Thanks!
