### ISSUE TITLE
New tour step creation requires two clicks. Preview mode doesn't change after adding step to tour.

### ISSUE THREAD

**Issue by gsmile** [microsoft/codetour#93]
When creating new tour, a new step takes 2 clicks to add, which the user sees as a bug.

The first button says: Add step to tour
The second button says: Save tour

The user must press both buttons in sequential order to add a step and move on with tour or code editing.

Expected experience: Adding a tour requires one button click, which says Add Step to Tour, to change the tour dialogue box from Editing to Viewing
To get back to the editing box, the customer will press the Pencil icon on top of the box

Screenshot of Button
![add_step](https://user-images.githubusercontent.com/12738587/94345866-eeb37f00-fff6-11ea-8de0-55aa7a41bbbc.jpg)

![save_step](https://user-images.githubusercontent.com/12738587/94345828-b744d280-fff6-11ea-954f-de51b0d851df.jpg)

Gif:
![double_click_submit](https://user-images.githubusercontent.com/12738587/94344866-5b774b00-fff0-11ea-997c-e5a5412978e3.gif)

**Comment by RandomFractals** [comment]
not sure if @gsmile  picked it from my first impression shares & I don't know what's the good solution is there since we can't just save that new step md on enter.

seeing created steps in edit mode was weird tho.

sorry, I am pressed on time on other things, see #92 & our chares on twitter.

@gsmile thanks for logging this!

**Comment by gsmile** [comment]
@RandomFractals, thank you for the input! We are logging the issues to keep track of everything that needs to be done. The labels attached to the items help our team discuss and refer to the groups of issues.

**Comment by RandomFractals** [comment]
got it. I've never seen A, B, C grouping used for tagging github issues this way before. I like it! :)

**Comment by lostintangent** [comment]
@gsmile Just to confirm: the `Save Step` button isn't required to add a new step to the tour. Are you seeing otherwise? You should be able to click `Add Step to Tour` and then you're done. The `Save Step` button is there to allow you to _update_ the text of an existing step. So I could imagine that it would be more intuitive to change the text for this button to `Update Step`? But I want to make sure I'm not missing something if there's a bug somewhere.

**Comment by gsmile** [comment]
@lostintangent I have been told about a confusing experience where a dev needs to click two buttons in order to change the state of the tour step dialogue from editing to next step.

Here, I have included a screen capture of the bug where Add Step to Tour and Save Step are two required buttons to press to change the state of the dialogue box. The ideal experience is that a dev only presses one button to add a step which changes the state of the box from editing to viewing.
![double_click_submit](https://user-images.githubusercontent.com/12738587/94344866-5b774b00-fff0-11ea-997c-e5a5412978e3.gif)

**Comment by lostintangent** [comment]
This has been fixed in `v0.0.46`. Let me know if you have any other feedback!
